version: '3'

networks: 
  node-network:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - node-network